### ISSUE TITLE
Signal Clipping during EEG-fMRI?

### ISSUE THREAD

**Issue by jalevitt** [labstreaminglayer/App-BrainAmpSeries#9]
I've been trying trying to use this app in the context of simultaneous EEG-fMRI, which causes very high amplitude artifacts. However, these artifacts seem to be getting clipped by the app - the dynamic range seems to be limited +/- roughly 3000 uV. This is a problem as these artifacts cannot be properly removed if they have been clipped in this way. Do I simply need to increase the resolution using the menu option? Or is a more complex solution required?

Thanks for your help!

Edit - roughly 3000uv, not 300uv

**Comment by dmedine** [comment]
I have asked Brain Products for more information about this. In the meantime, can you please provide details about which version of the app you are using? There are now several different builds floating around.  Is it this one: https://github.com/labstreaminglayer/App-BrainAmpSeries/releases?

I forked this repository some time ago and made a version that has a downsampler (https://github.com/brain-products/LSL-BrainAmpSeries/releases/tag/v1.15.0). That may affect things.

One more question. Are you using the app with the Send Raw Stream box checked?
![brainapmp](https://user-images.githubusercontent.com/3613166/121281395-2c54ff80-c91b-11eb-978f-061073774ea4.png)

**Comment by jalevitt** [comment]
Thank you for your prompt reply! After doing some more investigation, it sound like changing the resolution probably is the easiest solution, although I'll have to wait until until I can test it again in the MR scanner. I'm not 100% sure what release I'm using because I can't find a release number in any of my files, but given when I downloaded it (late november 2019) version 1.13.0 or something similar seems most likely. I have not been selecting the raw stream checkbox, as you indicate. 

I did some some back of the envelope calculation - assuming the app uses int16 to store the voltage values, a limit of ~ +/- 3000 uV makes sense given a resolution of 100nV : ((2^16)/2)/10 ~= 3000. So I assume this is just the problem, and changing the resolution should resolve it, albeit sacrificing some precision.

**Comment by dmedine** [comment]
Ah, yes. 3000 micro volts makes more sense.

I took this to Brain Products and they said that the BrainAmp should indeed use the 500 nanovolt resolution for MR applications. Your back of  the envelope calculations are pretty darn close. The 100 nanovolt resolution results in a dynamic range of ~3.3mV, and the 500 nanovolt resolution results in a range of ~16.4mv (roughly 5x as much---obviously). They also said that the 10 microvolt setting is are actually for experimental purposes only and should be removed from the app to avoid problems. The 152.6 microvolt setting is bizarre. I believe it is there for some legacy reason and may not even work.

I will make it more explicit in forthcoming versions of the app that 500 nV is to be used in the case of BrainAmp MR. Unless anyone out there objects, I will simply remove the other two settings. 

In any case using the 500 nV setting will most likely solve your clipping issue.

However, the EEG/fMRI guru at Brain Products (Tracy Warbrick) mentioned that it could be possible that 'some setup or sequence issues might be causing a gradient artifact saturation problems'. If you are still experiencing clipped artifacts at the higher dynamic range, it could be a hardware/setup problem rather than the resolution. In this case, you will need to contact technical support at Brain Products or your dealer (BV LLC?) and see what they can do to help.

**Comment by jalevitt** [comment]
Thanks again for your help! This makes sense, I will give the 500nV res setting a try next time I get the chance

**Comment by jalevitt** [comment]
So I just had the chance to revisit this in the MR scanner. I don't think the resolution is the fix - it is starting to seem like there's a bug somewhere. Here are histograms of the signal amplitude from consecutive recordings, one done in Brainvision Recorder with 500nv resolution, the other with LSL  with 500nv Resolution - x axis is in uV. It's easy to see that the signal collected with LSL is getting clipped, the one from Brainvision isn't (or at least barely). Could this be a version issue? Have there been any changes to how resolution is implemented since v1.13.0? I'll try it out with 1.15.0 when I get the chance I guess. Unfortunately my C++ skills aren't strong enough to really sort this out on my own
![RTEEG09R5_hist](https://user-images.githubusercontent.com/62147731/126693011-898c1d8b-9a9f-4770-9f34-5c225bea509e.jpg)
![RTEEG09R2_hist](https://user-images.githubusercontent.com/62147731/126693013-ba05a5f9-9ea4-4537-91b2-fcc14c7dbe65.jpg)

**Comment by dmedine** [comment]
I am sorry that this is still causing you grief. 

I have a couple of questions about the histograms shown here. Are the binned items instantaneous amplitudes (i.e. sample values)? It also seems that apart from the spikes at the ends of the dynamic range the histograms are quite different. How was this data collected? Was this from actual EEG on a subject in the scanner?

I assume you were using the same sampling rate in both recordings? 

 The only other thing that I can think of is that this line (https://github.com/brain-products/LSL-BrainAmpSeries/blob/master/mainwindow.cpp#L449) is causing the scale to be 1 instead of .5. Unfortunately, I do not have a BrainAmp device to test with at the moment. @tstenner: can you please verify that the channel scale is being properly set? From reading the code I don't see why it could possibly be wrong but I dare not say that it isn't working as expected without stepping through with the debugger. @jalevitt  you might be able to verify this as well. If the signal amplitude (in general) is 2x as great as you expect then this might be a bug.

Again, this version of the app is fast becoming more and more deprecated. The current version is here: https://github.com/brain-products/LSL-BrainAmpSeries/releases/tag/v1.15.1. I recently pushed a new release that corrected an issue involving the downsampling filters which were not matching Recorder's implementation.  This could cause issues. The filters were set to the wrong sampling rate and it could be that if you were downsampling to something low, that the artifact might cause the filter to ring at a low frequency and cause these amplitude spikes. However, if you were using <=v1.13, the downsamplers were not yet implemented.

**Comment by jalevitt** [comment]
Thanks for getting back to me, I appreciate you're helping me out with this. In response to your questions:

> Are the binned items instantaneous amplitudes (i.e. sample values)?

Yes, exactly. 

> How was this data collected? Was this from actual EEG on a subject in the scanner?

This data was collected from a human subject inside a siemens 3T MRI scanner at resting state. The recording are separated by a couple minutes, but otherwise nothing is changed between them. The same MR sequence was used in both cases. No pre-processing was applied to either dataset, and no downsampling. They are both at 5000hz sampling.

As I've spent more time with these recordings, I've noticed something else pretty strange: the gradient artifact waveform in the two recordings is extremely different - see figures, y axis is in uV, x axis is in samples. I would generally expect this to be very constant, given the same MR sequence. The stark difference makes me think that something pretty odd is happening that probably could not be explained just by a 0.5x or 2x error. 

In any case, I might have a chance to test this out again next week, so maybe I'll try v1.15.0 and see if that makes a difference.
![BrainvisionRecorderGradient](https://user-images.githubusercontent.com/62147731/126729679-ebddd12c-c03e-4cb7-9329-ab3a27d0e058.jpg)
![LSLGradient](https://user-images.githubusercontent.com/62147731/126729681-9d635921-496d-4b50-84bb-5da3eb1ebf0a.jpg)

**Comment by dmedine** [comment]
OK, obviously this is not x2 error. Do you have any data to compare that was not done in the scanner? I would expect that you would have exactly the same discrepancies in that scenario. The testing that I have done using v1.15.1 did not show any inconsistencies compared with Recorder, although it was not done in a scanner.

**Comment by dmedine** [comment]
One other thing, can you check your vhdr file and confirm that the unit of measure is micro volts?

**Comment by jalevitt** [comment]
I checked the vhdr, can confirm its in uV.

> Do you have any data to compare that was not done in the scanner? 

 I have some other data from a previous subject with both LSL and Recorder; it's still inside the scanner but with the gradient turned off, so there's no high amplitude artifact. Those two recording are qualitatively very similar, with no real difference in amplitude and basically similar waveforms. I could attach figures if interested, but they are basically unsuspicious IMO. The resolution was 500nV in both cases. I'm not really sure how to explain this. Is there any way that the LSL app could be working correctly with data near the middle of its dynamic range, but not correctly with data near the edge? It's very odd.

**Comment by dmedine** [comment]
I have been in touch with one of the engineers at BrainProducts who had an insight. If you are recording at <= 1kHz in Recorder the downsampling filters may be what is causing the gradient to be attenuated. You can try the newest version of the app (https://github.com/brain-products/LSL-BrainAmpSeries/releases/tag/v1.15.1) which does have downsampling implemented more or less the same as it is done in BV Recorder.

**Comment by dmedine** [comment]
But, I believe the recommended sampling rate for artifact removal in the scanner is 5kHz, so maybe this has nothing to do with it. It certainly shouldn't be saturating the raw data, though.

**Comment by dmedine** [comment]
@jalevitt I think I have found the problem. Apparently there is a hardware filter that the LSL app does not set properly in the case of BrainAmp MR. According to folks at BrainProducts, if the hardware filter is set to 1kHz (which it is in the LSL connector app) this saturation is likely to occur. I am going to make a patch for the app and when it is done I will notify you.

**Comment by dmedine** [comment]
@jalevitt here is a link to a beta version with the MR filter patch inside: https://drive.google.com/file/d/1lAulEWG2xUCsxhBpi1hQpw5rSXzXcYKU/view?usp=sharing. The hardware filter parameter is hard-coded so the app will only work with BrainAmpMR. According to Brain Products this should stop the saturation issue with the gradient artifact. I will have access to actual BrainAmp devices in a few weeks. When I get my hands on the devices I will fix up the app so that this setting is controlled in a sensible way via the GUI and publish an official release. Since I have no device at the moment, there is a chance that this will not work, but it was a pretty simple patch so it should be ok. Please post here if it doesn't work and I will do whatever I can for you.

Again, I apologize for the problems. It appears that you are the first researcher to run BrainAmpMR in the scanner with LSL---so far no one had thought about this feature that is peculiar to BrainAmpMR. The price one pays for trailblazing, I guess.

**Comment by jalevitt** [comment]
Wow, thank you so much!! I really appreciate all the effort you've put in to helping me out with this. I was planning to do a scan this week so I could test this out, but we just had to send our amps in for repair, so it will have to wait for a bit. In any case, I'm excited to see what happens.

**Comment by dmedine** [comment]
I hope you get a chance to test it. I want to get this to be right! It is always difficult with MR applications because (obviously) testing in situ is always a challenge. I appreciate your effort here as well.

**Comment by jalevitt** [comment]
Our amps finally got repaired after 3+ months, so I've begun doing some testing outside the scanner before I test inside. I've think I've noticed an interesting bug in the new version that was not present in the old. When I set the Trigger Output Style to 'EEG Channel' (which is how I prefer to have it) the trigger channel behaves very strangely.  Here's a plot of the trigger data from a brief recording, which was conducted without any triggers actually being generated. My expectation based on using the old version, is that I would get all zeros here. Instead I get this:
![TriggerBug](https://user-images.githubusercontent.com/62147731/136092775-51218d31-bbae-4cef-86de-b63854282e26.jpg)


Any idea what might be the cause? Is it possible the trigger data is also getting sent through the hardware filter somehow?

**Comment by jalevitt** [comment]
Our amps finally got repaired after 3+ months, so I've begun doing some testing outside the scanner before I test inside. I've think I've noticed an interesting bug in the new version that was not present in the old. When I set the Trigger Output Style to 'EEG Channel' (which is how I prefer to have it) the trigger channel behaves very strangely. Here's a plot of the trigger data from a brief recording, which was conducted without any triggers actually being generated. My expectation based on using the old version, is that I would get all zeros here. Instead I get this:


![TriggerBug](https://user-images.githubusercontent.com/62147731/136094374-f670a64a-4492-4eef-8b29-84f9d9b7ba74.jpg)


It seems like the gap between the downward spikes is equal to the chunk size (32 samples). Any idea what might be the cause?

**Comment by dmedine** [comment]
I am going to close this issue because any fixes will not be made on this repository, but rather here: https://github.com/brain-products/LSL-BrainAmpSeries. I will start a new issue there that links to this thread. Also, the trigger issue is separate from the MR artifact saturation issue.

**Comment by dmedine** [comment]
This issue has been moved: https://github.com/brain-products/LSL-BrainAmpSeries/issues/4
